mindmap
%% Global (included in all views)
  root((Super_Platform))





    Engineering
      Services
        API_Gateway
        Auth
        Ingest
        Parse
      Data
        Store
        Event_Bus
